name: Deploy MDMA documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      
      - name: Build book
        run: mdbook build
      
      - name: Deploy to Droplet using SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          source: "book/*"
          target: "/var/www/html/mdbook"
          strip_components: 1
          rm: true
      
      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            echo "Reloading Nginx..."
            systemctl reload nginx